package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLockerOperation;
import org.linlinjava.litemall.db.domain.LitemallLockerOperationExample;

public interface LitemallLockerOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    long countByExample(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int insert(LitemallLockerOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLockerOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectOneByExample(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectOneByExampleSelective(@Param("example") LitemallLockerOperationExample example, @Param("selective") LitemallLockerOperation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectOneByExampleWithBLOBs(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    List<LitemallLockerOperation> selectByExampleSelective(@Param("example") LitemallLockerOperationExample example, @Param("selective") LitemallLockerOperation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    List<LitemallLockerOperation> selectByExampleWithBLOBs(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    List<LitemallLockerOperation> selectByExample(LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallLockerOperation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    LitemallLockerOperation selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLockerOperation record, @Param("example") LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallLockerOperation record, @Param("example") LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLockerOperation record, @Param("example") LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLockerOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallLockerOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLockerOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallLockerOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker_operation
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}