package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLocker;
import org.linlinjava.litemall.db.domain.LitemallLockerExample;

public interface LitemallLockerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    long countByExample(LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int insert(LitemallLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    LitemallLocker selectOneByExample(LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    LitemallLocker selectOneByExampleSelective(@Param("example") LitemallLockerExample example, @Param("selective") LitemallLocker.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    List<LitemallLocker> selectByExampleSelective(@Param("example") LitemallLockerExample example, @Param("selective") LitemallLocker.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    List<LitemallLocker> selectByExample(LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    LitemallLocker selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallLocker.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    LitemallLocker selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    LitemallLocker selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLocker record, @Param("example") LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLocker record, @Param("example") LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLocker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallLockerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}