package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class LitemallLockerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public LitemallLockerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public LitemallLockerExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public LitemallLockerExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        LitemallLockerExample example = new LitemallLockerExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public LitemallLockerExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public LitemallLockerExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Integer value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Integer value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Integer value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Integer value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStoreIdLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("store_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Integer> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Integer> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberIsNull() {
            addCriterion("cabinet_number is null");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberIsNotNull() {
            addCriterion("cabinet_number is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberEqualTo(String value) {
            addCriterion("cabinet_number =", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberNotEqualTo(String value) {
            addCriterion("cabinet_number <>", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberGreaterThan(String value) {
            addCriterion("cabinet_number >", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cabinet_number >=", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberLessThan(String value) {
            addCriterion("cabinet_number <", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberLessThanOrEqualTo(String value) {
            addCriterion("cabinet_number <=", value, "cabinetNumber");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCabinetNumberLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("cabinet_number <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCabinetNumberLike(String value) {
            addCriterion("cabinet_number like", value, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberNotLike(String value) {
            addCriterion("cabinet_number not like", value, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberIn(List<String> values) {
            addCriterion("cabinet_number in", values, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberNotIn(List<String> values) {
            addCriterion("cabinet_number not in", values, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberBetween(String value1, String value2) {
            addCriterion("cabinet_number between", value1, value2, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andCabinetNumberNotBetween(String value1, String value2) {
            addCriterion("cabinet_number not between", value1, value2, "cabinetNumber");
            return (Criteria) this;
        }

        public Criteria andZoneIsNull() {
            addCriterion("`zone` is null");
            return (Criteria) this;
        }

        public Criteria andZoneIsNotNull() {
            addCriterion("`zone` is not null");
            return (Criteria) this;
        }

        public Criteria andZoneEqualTo(String value) {
            addCriterion("`zone` =", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneNotEqualTo(String value) {
            addCriterion("`zone` <>", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThan(String value) {
            addCriterion("`zone` >", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThanOrEqualTo(String value) {
            addCriterion("`zone` >=", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneLessThan(String value) {
            addCriterion("`zone` <", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneLessThanOrEqualTo(String value) {
            addCriterion("`zone` <=", value, "zone");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andZoneLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`zone` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andZoneLike(String value) {
            addCriterion("`zone` like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotLike(String value) {
            addCriterion("`zone` not like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneIn(List<String> values) {
            addCriterion("`zone` in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotIn(List<String> values) {
            addCriterion("`zone` not in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneBetween(String value1, String value2) {
            addCriterion("`zone` between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotBetween(String value1, String value2) {
            addCriterion("`zone` not between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andStatusLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("`status` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIsNull() {
            addCriterion("current_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIsNotNull() {
            addCriterion("current_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdEqualTo(Integer value) {
            addCriterion("current_user_id =", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotEqualTo(Integer value) {
            addCriterion("current_user_id <>", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdGreaterThan(Integer value) {
            addCriterion("current_user_id >", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_user_id >=", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdLessThan(Integer value) {
            addCriterion("current_user_id <", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("current_user_id <=", value, "currentUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCurrentUserIdLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("current_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdIn(List<Integer> values) {
            addCriterion("current_user_id in", values, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotIn(List<Integer> values) {
            addCriterion("current_user_id not in", values, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdBetween(Integer value1, Integer value2) {
            addCriterion("current_user_id between", value1, value2, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andCurrentUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("current_user_id not between", value1, value2, "currentUserId");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdIsNull() {
            addCriterion("assigned_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdIsNotNull() {
            addCriterion("assigned_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdEqualTo(Integer value) {
            addCriterion("assigned_user_id =", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdNotEqualTo(Integer value) {
            addCriterion("assigned_user_id <>", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdGreaterThan(Integer value) {
            addCriterion("assigned_user_id >", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("assigned_user_id >=", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdLessThan(Integer value) {
            addCriterion("assigned_user_id <", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("assigned_user_id <=", value, "assignedUserId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedUserIdLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_user_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdIn(List<Integer> values) {
            addCriterion("assigned_user_id in", values, "assignedUserId");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdNotIn(List<Integer> values) {
            addCriterion("assigned_user_id not in", values, "assignedUserId");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdBetween(Integer value1, Integer value2) {
            addCriterion("assigned_user_id between", value1, value2, "assignedUserId");
            return (Criteria) this;
        }

        public Criteria andAssignedUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("assigned_user_id not between", value1, value2, "assignedUserId");
            return (Criteria) this;
        }

        public Criteria andAssignedAtIsNull() {
            addCriterion("assigned_at is null");
            return (Criteria) this;
        }

        public Criteria andAssignedAtIsNotNull() {
            addCriterion("assigned_at is not null");
            return (Criteria) this;
        }

        public Criteria andAssignedAtEqualTo(LocalDateTime value) {
            addCriterion("assigned_at =", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtNotEqualTo(LocalDateTime value) {
            addCriterion("assigned_at <>", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtGreaterThan(LocalDateTime value) {
            addCriterion("assigned_at >", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("assigned_at >=", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtLessThan(LocalDateTime value) {
            addCriterion("assigned_at <", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("assigned_at <=", value, "assignedAt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAssignedAtLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("assigned_at <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAssignedAtIn(List<LocalDateTime> values) {
            addCriterion("assigned_at in", values, "assignedAt");
            return (Criteria) this;
        }

        public Criteria andAssignedAtNotIn(List<LocalDateTime> values) {
            addCriterion("assigned_at not in", values, "assignedAt");
            return (Criteria) this;
        }

        public Criteria andAssignedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("assigned_at between", value1, value2, "assignedAt");
            return (Criteria) this;
        }

        public Criteria andAssignedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("assigned_at not between", value1, value2, "assignedAt");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeIsNull() {
            addCriterion("last_used_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeIsNotNull() {
            addCriterion("last_used_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeEqualTo(LocalDateTime value) {
            addCriterion("last_used_time =", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeNotEqualTo(LocalDateTime value) {
            addCriterion("last_used_time <>", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeGreaterThan(LocalDateTime value) {
            addCriterion("last_used_time >", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_used_time >=", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeLessThan(LocalDateTime value) {
            addCriterion("last_used_time <", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_used_time <=", value, "lastUsedTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLastUsedTimeLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("last_used_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeIn(List<LocalDateTime> values) {
            addCriterion("last_used_time in", values, "lastUsedTime");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeNotIn(List<LocalDateTime> values) {
            addCriterion("last_used_time not in", values, "lastUsedTime");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_used_time between", value1, value2, "lastUsedTime");
            return (Criteria) this;
        }

        public Criteria andLastUsedTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_used_time not between", value1, value2, "lastUsedTime");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysIsNull() {
            addCriterion("clean_alert_days is null");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysIsNotNull() {
            addCriterion("clean_alert_days is not null");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysEqualTo(Integer value) {
            addCriterion("clean_alert_days =", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysNotEqualTo(Integer value) {
            addCriterion("clean_alert_days <>", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysGreaterThan(Integer value) {
            addCriterion("clean_alert_days >", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("clean_alert_days >=", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysLessThan(Integer value) {
            addCriterion("clean_alert_days <", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysLessThanOrEqualTo(Integer value) {
            addCriterion("clean_alert_days <=", value, "cleanAlertDays");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andCleanAlertDaysLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("clean_alert_days <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysIn(List<Integer> values) {
            addCriterion("clean_alert_days in", values, "cleanAlertDays");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysNotIn(List<Integer> values) {
            addCriterion("clean_alert_days not in", values, "cleanAlertDays");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysBetween(Integer value1, Integer value2) {
            addCriterion("clean_alert_days between", value1, value2, "cleanAlertDays");
            return (Criteria) this;
        }

        public Criteria andCleanAlertDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("clean_alert_days not between", value1, value2, "cleanAlertDays");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("notes =", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("notes <>", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("notes >", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("notes >=", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("notes <", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("notes <=", value, "notes");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andNotesLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("notes <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("notes not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(LocalDateTime value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(LocalDateTime value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(LocalDateTime value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andAddTimeLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("add_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<LocalDateTime> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andUpdateTimeLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("update_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(LitemallLocker.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_locker
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private LitemallLockerExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        protected Criteria(LitemallLockerExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public LitemallLockerExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(LitemallLocker.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(LitemallLocker.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table litemall_locker
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.LitemallLockerExample example);
    }
}