package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallLocker {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.cabinet_number
     *
     * @mbg.generated
     */
    private String cabinetNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.zone
     *
     * @mbg.generated
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.current_user_id
     *
     * @mbg.generated
     */
    private Integer currentUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.assigned_user_id
     *
     * @mbg.generated
     */
    private Integer assignedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.assigned_at
     *
     * @mbg.generated
     */
    private LocalDateTime assignedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.last_used_time
     *
     * @mbg.generated
     */
    private LocalDateTime lastUsedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.clean_alert_days
     *
     * @mbg.generated
     */
    private Integer cleanAlertDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_locker.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * Transient field for storing the store name (not persisted to database)
     */
    private transient String storeName;

    /**
     * Transient field alias for cabinetNumber to support legacy code
     */
    private transient String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.id
     *
     * @return the value of litemall_locker.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.id
     *
     * @param id the value for litemall_locker.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.store_id
     *
     * @return the value of litemall_locker.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.store_id
     *
     * @param storeId the value for litemall_locker.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.cabinet_number
     *
     * @return the value of litemall_locker.cabinet_number
     *
     * @mbg.generated
     */
    public String getCabinetNumber() {
        return cabinetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.cabinet_number
     *
     * @param cabinetNumber the value for litemall_locker.cabinet_number
     *
     * @mbg.generated
     */
    public void setCabinetNumber(String cabinetNumber) {
        this.cabinetNumber = cabinetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.zone
     *
     * @return the value of litemall_locker.zone
     *
     * @mbg.generated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.zone
     *
     * @param zone the value for litemall_locker.zone
     *
     * @mbg.generated
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.status
     *
     * @return the value of litemall_locker.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.status
     *
     * @param status the value for litemall_locker.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.current_user_id
     *
     * @return the value of litemall_locker.current_user_id
     *
     * @mbg.generated
     */
    public Integer getCurrentUserId() {
        return currentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.current_user_id
     *
     * @param currentUserId the value for litemall_locker.current_user_id
     *
     * @mbg.generated
     */
    public void setCurrentUserId(Integer currentUserId) {
        this.currentUserId = currentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.assigned_user_id
     *
     * @return the value of litemall_locker.assigned_user_id
     *
     * @mbg.generated
     */
    public Integer getAssignedUserId() {
        return assignedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.assigned_user_id
     *
     * @param assignedUserId the value for litemall_locker.assigned_user_id
     *
     * @mbg.generated
     */
    public void setAssignedUserId(Integer assignedUserId) {
        this.assignedUserId = assignedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.assigned_at
     *
     * @return the value of litemall_locker.assigned_at
     *
     * @mbg.generated
     */
    public LocalDateTime getAssignedAt() {
        return assignedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.assigned_at
     *
     * @param assignedAt the value for litemall_locker.assigned_at
     *
     * @mbg.generated
     */
    public void setAssignedAt(LocalDateTime assignedAt) {
        this.assignedAt = assignedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.last_used_time
     *
     * @return the value of litemall_locker.last_used_time
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUsedTime() {
        return lastUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.last_used_time
     *
     * @param lastUsedTime the value for litemall_locker.last_used_time
     *
     * @mbg.generated
     */
    public void setLastUsedTime(LocalDateTime lastUsedTime) {
        this.lastUsedTime = lastUsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.clean_alert_days
     *
     * @return the value of litemall_locker.clean_alert_days
     *
     * @mbg.generated
     */
    public Integer getCleanAlertDays() {
        return cleanAlertDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.clean_alert_days
     *
     * @param cleanAlertDays the value for litemall_locker.clean_alert_days
     *
     * @mbg.generated
     */
    public void setCleanAlertDays(Integer cleanAlertDays) {
        this.cleanAlertDays = cleanAlertDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.notes
     *
     * @return the value of litemall_locker.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.notes
     *
     * @param notes the value for litemall_locker.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.add_time
     *
     * @return the value of litemall_locker.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.add_time
     *
     * @param addTime the value for litemall_locker.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.update_time
     *
     * @return the value of litemall_locker.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.update_time
     *
     * @param updateTime the value for litemall_locker.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_locker.deleted
     *
     * @return the value of litemall_locker.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_locker.deleted
     *
     * @param deleted the value for litemall_locker.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Get the transient store name
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * Set the transient store name
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * Get number (alias for cabinetNumber)
     */
    public String getNumber() {
        return getCabinetNumber();
    }

    /**
     * Set number (alias for cabinetNumber)
     */
    public void setNumber(String number) {
        setCabinetNumber(number);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", cabinetNumber=").append(cabinetNumber);
        sb.append(", zone=").append(zone);
        sb.append(", status=").append(status);
        sb.append(", currentUserId=").append(currentUserId);
        sb.append(", assignedUserId=").append(assignedUserId);
        sb.append(", assignedAt=").append(assignedAt);
        sb.append(", lastUsedTime=").append(lastUsedTime);
        sb.append(", cleanAlertDays=").append(cleanAlertDays);
        sb.append(", notes=").append(notes);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallLocker other = (LitemallLocker) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getCabinetNumber() == null ? other.getCabinetNumber() == null : this.getCabinetNumber().equals(other.getCabinetNumber()))
            && (this.getZone() == null ? other.getZone() == null : this.getZone().equals(other.getZone()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCurrentUserId() == null ? other.getCurrentUserId() == null : this.getCurrentUserId().equals(other.getCurrentUserId()))
            && (this.getAssignedUserId() == null ? other.getAssignedUserId() == null : this.getAssignedUserId().equals(other.getAssignedUserId()))
            && (this.getAssignedAt() == null ? other.getAssignedAt() == null : this.getAssignedAt().equals(other.getAssignedAt()))
            && (this.getLastUsedTime() == null ? other.getLastUsedTime() == null : this.getLastUsedTime().equals(other.getLastUsedTime()))
            && (this.getCleanAlertDays() == null ? other.getCleanAlertDays() == null : this.getCleanAlertDays().equals(other.getCleanAlertDays()))
            && (this.getNotes() == null ? other.getNotes() == null : this.getNotes().equals(other.getNotes()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getCabinetNumber() == null) ? 0 : getCabinetNumber().hashCode());
        result = prime * result + ((getZone() == null) ? 0 : getZone().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCurrentUserId() == null) ? 0 : getCurrentUserId().hashCode());
        result = prime * result + ((getAssignedUserId() == null) ? 0 : getAssignedUserId().hashCode());
        result = prime * result + ((getAssignedAt() == null) ? 0 : getAssignedAt().hashCode());
        result = prime * result + ((getLastUsedTime() == null) ? 0 : getLastUsedTime().hashCode());
        result = prime * result + ((getCleanAlertDays() == null) ? 0 : getCleanAlertDays().hashCode());
        result = prime * result + ((getNotes() == null) ? 0 : getNotes().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_locker
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        storeId("store_id", "storeId", "INTEGER", false),
        cabinetNumber("cabinet_number", "cabinetNumber", "VARCHAR", false),
        zone("zone", "zone", "VARCHAR", true),
        status("status", "status", "VARCHAR", true),
        currentUserId("current_user_id", "currentUserId", "INTEGER", false),
        assignedUserId("assigned_user_id", "assignedUserId", "INTEGER", false),
        assignedAt("assigned_at", "assignedAt", "TIMESTAMP", false),
        lastUsedTime("last_used_time", "lastUsedTime", "TIMESTAMP", false),
        cleanAlertDays("clean_alert_days", "cleanAlertDays", "INTEGER", false),
        notes("notes", "notes", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_locker
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}